### PR TITLE
feat: allow class fields resolvers and support inheritance from class prototype

### PR DESCRIPTION
**Pull request by targos**
Walk the prototype chain until we reach null or Object.prototype (which is ignored).

Closes: https://github.com/zakodium/adonis-apollo/issues/59

### CODE REVIEW

**Review by tpoisseau — APPROVED** [review]
SGTM, I just wonder how it goes with inheritance (super) or context (this).

```js
class ResolverA {
  foo() {return 'foo'}
}

class ResolverB {
  foo() {return `${super.foo()} bar`}
}
```

```js
class Resolver {
  #helper() {return 'something'}
  
  foo() {return this.#helper()}
}
```

Ability to use `super`, I think it's not important, I'm not convinced inheritance is pertinent for graphql resolvers.

But I think it's important we can use the context `this` in our class resolvers. to internalize helpers for example.

**Comment by targos** [comment]
It should work, I will modify the test to show it.

**Comment by targos** [comment]
Test updated. Does it cover everything you had in mind?

**Review by tpoisseau — APPROVED** [review]
Yes, SGTM

**Comment by targos** [comment]
Released

**Pull request merged**
